project:
  type: website

website:
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: join.qmd
        text: JOIN
      - href: blog/indexblog.qmd
        text: BLOG
      - href: team.qmd
        text: TEAM
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
